name: Integration Worklfow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up CMake
        run: |
          brew install cmake

      - name: install dependencies
        run: | 
          brew install eigen
          brew install googletest

      - name: make
        run: |
          make clean
          make

      - name: test
        run: |
          make test
          
